/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CS234_Project;

import static CS234_Project.Cars.getCarsList;
import static CS234_Project.Clients.getClientsList;
import static CS234_Project.Employees.getEmployeeList;
import java.util.ArrayList;

/**
 *
 * @author wyatt
 */
public class CS234_GUI extends javax.swing.JFrame {

    /**
     * Creates new form CS234_GUI
     */
    public CS234_GUI() {
        initComponents();
    }
    
    public static void Run(){
        new CS234_GUI().setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Main = new javax.swing.JTabbedPane();
        EmployeePanel = new javax.swing.JTabbedPane();
        AddEmployeePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        EmployeeNameAdd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        EmployeeSalaryAdd = new javax.swing.JTextField();
        AddEmployeeButton = new javax.swing.JButton();
        EditEmployeePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NewSalary = new javax.swing.JTextField();
        UpdateEmployeeButton = new javax.swing.JButton();
        UpdateEmployeeBox = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        EmployeeSearchField = new javax.swing.JTextField();
        EmployeeSearchButton = new javax.swing.JButton();
        RefreshEmployeeCatalogue = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        EmployeeCatalogue = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        RemoveEmployeeButton = new javax.swing.JButton();
        RemoveEmployeeBox = new javax.swing.JComboBox<>();
        CarPanel = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        CarMake = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CarModel = new javax.swing.JTextField();
        AddCarButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        UpdateCarBox = new javax.swing.JComboBox<>();
        UpdateMakeField = new javax.swing.JTextField();
        UpdateModelFeild = new javax.swing.JTextField();
        UpdateCarButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        SearchCarField = new javax.swing.JTextField();
        SearchCarButton = new javax.swing.JButton();
        RefreshCarCatalogue = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        CarCatalogue = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        DeleteCarBox = new javax.swing.JComboBox<>();
        DeleteCarButton = new javax.swing.JButton();
        ClientPanel = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        AddClientName = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        AddClientVehicle = new javax.swing.JComboBox<>();
        AddClientButton = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        UpdateClientBox = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        UpdateClientVehicle = new javax.swing.JComboBox<>();
        UpdateClientButton = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        SearchClientField = new javax.swing.JTextField();
        SearchClientButton = new javax.swing.JButton();
        ClientCatalogueButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        ClientCatalogue = new javax.swing.JTextArea();
        jPanel10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        RemoveClientBox = new javax.swing.JComboBox<>();
        RemoveClientButton = new javax.swing.JButton();
        ServicesPanel = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        AddServiceEmployee = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        AddServiceClient = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        AddServiceProblem = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        AddServiceCost = new javax.swing.JTextField();
        AddServiceButton = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        RefreshServiceCatalogue = new javax.swing.JButton();
        SearchServiceButton = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        ServiceCatalogue = new javax.swing.JTextArea();
        jPanel14 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        RemoveServiceBox = new javax.swing.JComboBox<>();
        RemoveServiceButton = new javax.swing.JButton();
        AppointmentPanel = new javax.swing.JTabbedPane();
        ReportPanel = new javax.swing.JTabbedPane();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Name");

        EmployeeNameAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeNameAddActionPerformed(evt);
            }
        });

        jLabel3.setText("Salary");

        AddEmployeeButton.setText("Add Employee");
        AddEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmployeeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddEmployeePanelLayout = new javax.swing.GroupLayout(AddEmployeePanel);
        AddEmployeePanel.setLayout(AddEmployeePanelLayout);
        AddEmployeePanelLayout.setHorizontalGroup(
            AddEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddEmployeePanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(AddEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddEmployeeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                    .addGroup(AddEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(EmployeeNameAdd)
                        .addComponent(EmployeeSalaryAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)))
                .addGap(0, 175, Short.MAX_VALUE))
        );
        AddEmployeePanelLayout.setVerticalGroup(
            AddEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddEmployeePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeeNameAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(AddEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(EmployeeSalaryAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AddEmployeeButton)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        EmployeePanel.addTab("Add Employee", AddEmployeePanel);

        jLabel1.setText("Employee");

        jLabel4.setText("New Salary");

        UpdateEmployeeButton.setText("Update Employee");
        UpdateEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateEmployeeButtonActionPerformed(evt);
            }
        });

        for(Employees employee:Employees.getEmployeeList()){
            UpdateEmployeeBox.addItem(employee.getEmployeeName());
        }
        UpdateEmployeeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateEmployeeBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EditEmployeePanelLayout = new javax.swing.GroupLayout(EditEmployeePanel);
        EditEmployeePanel.setLayout(EditEmployeePanelLayout);
        EditEmployeePanelLayout.setHorizontalGroup(
            EditEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditEmployeePanelLayout.createSequentialGroup()
                .addGroup(EditEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EditEmployeePanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditEmployeePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(7, 7, 7)))
                .addGroup(EditEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UpdateEmployeeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NewSalary, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addComponent(UpdateEmployeeBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        EditEmployeePanelLayout.setVerticalGroup(
            EditEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditEmployeePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EditEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(UpdateEmployeeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EditEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(NewSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(UpdateEmployeeButton)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        EmployeePanel.addTab("Edit Employee", EditEmployeePanel);

        jLabel6.setText("Search Employees");

        EmployeeSearchButton.setText("Search");
        EmployeeSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeSearchButtonActionPerformed(evt);
            }
        });

        RefreshEmployeeCatalogue.setText("Refresh Catalogue");
        RefreshEmployeeCatalogue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshEmployeeCatalogueActionPerformed(evt);
            }
        });

        EmployeeCatalogue.setColumns(20);
        EmployeeCatalogue.setRows(5);
        jScrollPane2.setViewportView(EmployeeCatalogue);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RefreshEmployeeCatalogue)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(EmployeeSearchField)
                        .addGap(18, 18, 18)
                        .addComponent(EmployeeSearchButton))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(EmployeeSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployeeSearchButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(RefreshEmployeeCatalogue))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                .addContainerGap())
        );

        EmployeePanel.addTab("Employee Catalogue", jPanel1);

        jLabel7.setText("Employee");

        RemoveEmployeeButton.setText("Remove");
        RemoveEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveEmployeeButtonActionPerformed(evt);
            }
        });

        RemoveEmployeeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveEmployeeBoxActionPerformed(evt);
            }
        });
        for(Employees employee:Employees.getEmployeeList()){
            RemoveEmployeeBox.addItem(employee.getEmployeeName());
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RemoveEmployeeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(RemoveEmployeeBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(RemoveEmployeeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(RemoveEmployeeButton)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        EmployeePanel.addTab("Remove Employee", jPanel2);

        Main.addTab("Employees", EmployeePanel);

        jLabel5.setText("Make");

        CarMake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarMakeActionPerformed(evt);
            }
        });

        jLabel8.setText("Model");

        AddCarButton.setText("Add Car");
        AddCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CarMake, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddCarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(CarModel, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CarMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CarModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AddCarButton)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        CarPanel.addTab("Add Car", jPanel3);

        jLabel9.setText("New Make");

        jLabel10.setText("New Model");

        jLabel11.setText("Car");

        UpdateCarBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateCarBoxActionPerformed(evt);
            }
        });
        for(Cars car: Cars.getCarsList()){
            UpdateCarBox.addItem("Make: " + car.getMake() +" Model: " + car.getModel());
        }

        UpdateCarButton.setText("Update");
        UpdateCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateCarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UpdateCarBox, 0, 266, Short.MAX_VALUE)
                            .addComponent(UpdateMakeField)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UpdateCarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UpdateModelFeild))))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(UpdateCarBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(UpdateMakeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(UpdateModelFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(UpdateCarButton)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        CarPanel.addTab("Update Car", jPanel4);

        jLabel12.setText("Search Cars");

        SearchCarButton.setText("Search");
        SearchCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchCarButtonActionPerformed(evt);
            }
        });

        RefreshCarCatalogue.setText("Refresh Catalogue");
        RefreshCarCatalogue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshCarCatalogueActionPerformed(evt);
            }
        });

        CarCatalogue.setColumns(20);
        CarCatalogue.setRows(5);
        jScrollPane3.setViewportView(CarCatalogue);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RefreshCarCatalogue)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(SearchCarField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchCarButton))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(SearchCarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchCarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(RefreshCarCatalogue))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                .addContainerGap())
        );

        CarPanel.addTab("Car Catalogue", jPanel5);

        jLabel13.setText("Car");

        DeleteCarBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteCarBoxActionPerformed(evt);
            }
        });
        for(Cars car: Cars.getCarsList()){
            DeleteCarBox.addItem("Make: " + car.getMake() +" Model: " + car.getModel());
        }

        DeleteCarButton.setText("Remove");
        DeleteCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteCarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DeleteCarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                    .addComponent(DeleteCarBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(DeleteCarBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(DeleteCarButton)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        CarPanel.addTab("Remove Car", jPanel6);

        Main.addTab("Cars", CarPanel);

        jLabel14.setText("Name");

        jLabel15.setText("Vehicle");

        AddClientVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddClientVehicleActionPerformed(evt);
            }
        });
        for(Cars car: Cars.getCarsList()){
            AddClientVehicle.addItem("Make: " + car.getMake() +" Model: " + car.getModel());
        }

        AddClientButton.setText("Add Client");
        AddClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddClientButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(AddClientName, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AddClientButton, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                            .addComponent(AddClientVehicle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(AddClientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(AddClientVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AddClientButton)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        ClientPanel.addTab("Add Client", jPanel7);

        jLabel16.setText("Client");

        for(Clients client: Clients.getClientsList()){
            UpdateClientBox.addItem(client.getClientName());
        }

        jLabel17.setText("New Vehicle");

        for(Cars car: Cars.getCarsList()){
            UpdateClientVehicle.addItem("Make: " + car.getMake() +" Model: " + car.getModel());
        }

        UpdateClientButton.setText("Update Client");
        UpdateClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateClientButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UpdateClientButton, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(UpdateClientBox, 0, 242, Short.MAX_VALUE)
                        .addComponent(UpdateClientVehicle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(UpdateClientBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(UpdateClientVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(UpdateClientButton)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        ClientPanel.addTab("Update Client", jPanel8);

        jLabel18.setText("Search Clients");

        SearchClientField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchClientFieldActionPerformed(evt);
            }
        });

        SearchClientButton.setText("Search");
        SearchClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchClientButtonActionPerformed(evt);
            }
        });

        ClientCatalogueButton.setText("Refresh Catalogue");
        ClientCatalogueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientCatalogueButtonActionPerformed(evt);
            }
        });

        ClientCatalogue.setColumns(20);
        ClientCatalogue.setRows(5);
        jScrollPane4.setViewportView(ClientCatalogue);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ClientCatalogueButton)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(SearchClientField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchClientButton))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(SearchClientField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchClientButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ClientCatalogueButton))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addContainerGap())
        );

        ClientPanel.addTab("Client Catalogue", jPanel9);

        jLabel19.setText("Client");

        for(Clients client: Clients.getClientsList()){
            RemoveClientBox.addItem(client.getClientName());
        }

        RemoveClientButton.setText("Remove Client");
        RemoveClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveClientButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RemoveClientButton, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                    .addComponent(RemoveClientBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(RemoveClientBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(RemoveClientButton)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        ClientPanel.addTab("Remove Client", jPanel10);

        Main.addTab("Clients", ClientPanel);

        jLabel20.setText("Employee");

        for(Employees employee:Employees.getEmployeeList()){
            AddServiceEmployee.addItem(employee.getEmployeeName());
        }

        jLabel21.setText("Client");

        for(Clients client: Clients.getClientsList()){
            AddServiceClient.addItem(client.getClientName());
        }

        AddServiceProblem.setColumns(20);
        AddServiceProblem.setRows(5);
        jScrollPane5.setViewportView(AddServiceProblem);

        jLabel22.setText("What does the client say is wrong with their vehicle");

        jLabel23.setText("Cost");

        AddServiceButton.setText("Add");
        AddServiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddServiceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(0, 135, Short.MAX_VALUE))
                    .addComponent(jScrollPane5)
                    .addComponent(AddServiceEmployee, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddServiceClient, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(AddServiceCost)
                        .addGap(18, 18, 18)
                        .addComponent(AddServiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddServiceEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddServiceClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddServiceCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(AddServiceButton))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        ServicesPanel.addTab("Add Service", jPanel11);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        ServicesPanel.addTab("Update Service", jPanel12);

        jLabel24.setText("Search Services");

        RefreshServiceCatalogue.setText("Refresh ");
        RefreshServiceCatalogue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshServiceCatalogueActionPerformed(evt);
            }
        });

        SearchServiceButton.setText("Search");

        ServiceCatalogue.setColumns(20);
        ServiceCatalogue.setLineWrap(true);
        ServiceCatalogue.setRows(5);
        jScrollPane7.setViewportView(ServiceCatalogue);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(RefreshServiceCatalogue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jTextField1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchServiceButton))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SearchServiceButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RefreshServiceCatalogue)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ServicesPanel.addTab("Service Catalogue", jPanel13);

        jLabel25.setText("Service");

        RemoveServiceBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        RemoveServiceButton.setText("Remove");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RemoveServiceButton, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                    .addComponent(RemoveServiceBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(RemoveServiceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RemoveServiceButton)
                .addContainerGap(234, Short.MAX_VALUE))
        );

        ServicesPanel.addTab("Remove Service", jPanel14);

        Main.addTab("Services", ServicesPanel);
        Main.addTab("Appointments", AppointmentPanel);
        Main.addTab("Reports", ReportPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /***************************************************************************************************
     * This is where My code starts
     * @param evt 
     ***************************************************************************************************/
  
    private void AddEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmployeeButtonActionPerformed
        String employeeName = EmployeeNameAdd.getText();
        double employeeSalary = Double.parseDouble(EmployeeSalaryAdd.getText());
     
        Employees newEmployee = new Employees(employeeName,employeeSalary);
        Employees.getEmployeeList().add(newEmployee);
        
        EmployeeNameAdd.setText("");
        EmployeeSalaryAdd.setText("");
        
        updateEmployeePanel();
        
    }//GEN-LAST:event_AddEmployeeButtonActionPerformed

    private void EmployeeNameAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeNameAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeNameAddActionPerformed

    private void RefreshEmployeeCatalogueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshEmployeeCatalogueActionPerformed
        EmployeeCatalogue.setText("");
        for(Employees employee: Employees.getEmployeeList()){
            EmployeeCatalogue.append("Name: " + employee.getEmployeeName() + " | Salary: "+ employee.getEmployeeSalary() + "\n");
        }
    }//GEN-LAST:event_RefreshEmployeeCatalogueActionPerformed

    private void RemoveEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveEmployeeButtonActionPerformed
        int employeeIndex = RemoveEmployeeBox.getSelectedIndex();
        Employees employeeRemove = Employees.getEmployeeList().get(employeeIndex);
        
        Employees.getEmployeeList().remove(employeeRemove);
        
        updateEmployeePanel();
        
    }//GEN-LAST:event_RemoveEmployeeButtonActionPerformed

    private void EmployeeSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeSearchButtonActionPerformed
        EmployeeCatalogue.setText("");
        for(int i = 0; i < getEmployeeList().size();){

            if(getEmployeeList().get(i).getEmployeeName().equalsIgnoreCase(EmployeeSearchField.getText())){
                Employees employee = getEmployeeList().get(i);
                EmployeeCatalogue.setText("Name: " + employee.getEmployeeName() + 
                        " | Salary: "+ employee.getEmployeeSalary() + "\n");
                break;
            }else{
                i++;
            }
        }
    }//GEN-LAST:event_EmployeeSearchButtonActionPerformed

    private void RemoveEmployeeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveEmployeeBoxActionPerformed
        
    }//GEN-LAST:event_RemoveEmployeeBoxActionPerformed

    private void UpdateEmployeeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateEmployeeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateEmployeeBoxActionPerformed

    private void UpdateEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateEmployeeButtonActionPerformed
        int employeeIndex = UpdateEmployeeBox.getSelectedIndex();
        Employees employeeUpdate = Employees.getEmployeeList().get(employeeIndex);
        double newSalary = Double.parseDouble(NewSalary.getText());
        employeeUpdate.setEmployeeSalary(newSalary);
        
        NewSalary.setText("");
        
        updateEmployeePanel();
    }//GEN-LAST:event_UpdateEmployeeButtonActionPerformed
    
    private void updateEmployeePanel(){
        RemoveEmployeeBox.removeAllItems();
        for(Employees employee:Employees.getEmployeeList()){
            RemoveEmployeeBox.addItem(employee.getEmployeeName());
        }
        
        UpdateEmployeeBox.removeAllItems();
        for(Employees employee:Employees.getEmployeeList()){
            UpdateEmployeeBox.addItem(employee.getEmployeeName());
        }
        
        EmployeeCatalogue.setText("");
        for(Employees employee: Employees.getEmployeeList()){
            EmployeeCatalogue.append("Name: " + employee.getEmployeeName() + " | Salary: "+ employee.getEmployeeSalary() + "\n");
        }
    }
    
    /******************************************************
    *Below this is all the methods having to do with the Cars Class.
    */
  
    private void CarMakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarMakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarMakeActionPerformed

    private void AddCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCarButtonActionPerformed
        String make = CarMake.getText();
        String model = CarModel.getText();
        
        Cars newCar = new Cars(make,model);
        Cars.getCarsList().add(newCar);
        
        CarMake.setText("");
        CarModel.setText("");
        
        updateCarsPanel();
    }//GEN-LAST:event_AddCarButtonActionPerformed

    private void DeleteCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteCarButtonActionPerformed
        int carIndex = DeleteCarBox.getSelectedIndex();
        Cars removeCar = Cars.getCarsList().get(carIndex);
        
        Cars.getCarsList().remove(removeCar);
        
        CarCatalogue.setText("");
        for(Cars car: Cars.getCarsList()){
            CarCatalogue.append("Make: " + car.getMake() + " Model: " + car.getModel() + "\n");
        }
        
        DeleteCarBox.removeAllItems();
        for(Cars car: Cars.getCarsList()){
             DeleteCarBox.addItem("Make: " + car.getMake() +" Model: " + car.getModel());
        }
        
        updateCarsPanel();
    }//GEN-LAST:event_DeleteCarButtonActionPerformed

    private void RefreshCarCatalogueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshCarCatalogueActionPerformed
        CarCatalogue.setText("");
        for(Cars car: Cars.getCarsList()){
            CarCatalogue.append("Make: " + car.getMake() + " Model: " + car.getModel() + "\n");
        }
    }//GEN-LAST:event_RefreshCarCatalogueActionPerformed

    private void SearchCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchCarButtonActionPerformed
        CarCatalogue.setText("");
       for(int i = 0; i < getCarsList().size();){
            if(getCarsList().get(i).getMake().equalsIgnoreCase(SearchCarField.getText()))
            {
                Cars car = getCarsList().get(i);
                CarCatalogue.append("Make: " + car.getMake() + " Model: " +  car.getModel() + "\n");
            }
            i++;
        }
    }//GEN-LAST:event_SearchCarButtonActionPerformed

    private void DeleteCarBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteCarBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteCarBoxActionPerformed

    private void UpdateCarBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateCarBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateCarBoxActionPerformed

    private void UpdateCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateCarButtonActionPerformed
        int carIndex = UpdateCarBox.getSelectedIndex();
        Cars car = Cars.getCarsList().get(carIndex);
        
        if(UpdateMakeField.getText().isEmpty()){
            car.setModel(UpdateModelFeild.getText());
        }else if(UpdateModelFeild.getText().isEmpty()){
            car.setMake(UpdateMakeField.getText());
        }
        
        updateCarsPanel();
    }//GEN-LAST:event_UpdateCarButtonActionPerformed
    
    private void updateCarsPanel(){
        CarCatalogue.setText("");
        for(Cars car: Cars.getCarsList()){
            CarCatalogue.append("Make: " + car.getMake() + " Model: " + car.getModel() + "\n");
        }
        
        DeleteCarBox.removeAllItems();
        for(Cars car: Cars.getCarsList()){
             DeleteCarBox.addItem("Make: " + car.getMake() +" Model: " + car.getModel());
        }
        
        UpdateCarBox.removeAllItems();
        for(Cars car: Cars.getCarsList()){
             UpdateCarBox.addItem("Make: " + car.getMake() +" Model: " + car.getModel());
        }
        
        UpdateClientVehicle.removeAllItems();
        for(Cars car: Cars.getCarsList()){
             UpdateClientVehicle.addItem("Make: " + car.getMake() +" Model: " + car.getModel());
        }
        
        AddClientVehicle.removeAllItems();
        for(Cars car: Cars.getCarsList()){
             AddClientVehicle.addItem("Make: " + car.getMake() +" Model: " + car.getModel());
        }
    }
    
    /*********
     * Every method below this has to do with the clients class
     * @param evt 
     */
    private void SearchClientFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchClientFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchClientFieldActionPerformed

    private void AddClientVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddClientVehicleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddClientVehicleActionPerformed

    private void AddClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddClientButtonActionPerformed
        String name = AddClientName.getText();
        int carIndex = AddClientVehicle.getSelectedIndex();
        Cars car = Cars.getCarsList().get(carIndex);
        
        Clients client = new Clients(name,car);
        
        Clients.getClientsList().add(client);
        
        AddClientName.setText("");
        updateClientPanel();
    }//GEN-LAST:event_AddClientButtonActionPerformed

    private void ClientCatalogueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientCatalogueButtonActionPerformed
        ClientCatalogue.setText("");
        for(Clients client: Clients.getClientsList()){
            ClientCatalogue.append("Name: "+ client.getClientName() + " Vehicle: "  + client.getClientCar() + "\n");
        }
    }//GEN-LAST:event_ClientCatalogueButtonActionPerformed

    private void UpdateClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateClientButtonActionPerformed
        int clientIndex = UpdateClientBox.getSelectedIndex();
        Clients client = Clients.getClientsList().get(clientIndex);
        int vehicleIndex = UpdateClientVehicle.getSelectedIndex();
        Cars car = Cars.getCarsList().get(vehicleIndex);
        
        client.setClientCar(car);
        
        updateClientPanel();
    }//GEN-LAST:event_UpdateClientButtonActionPerformed

    private void RemoveClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveClientButtonActionPerformed
        int clientIndex = RemoveClientBox.getSelectedIndex();
        Clients client = Clients.getClientsList().get(clientIndex);
        
        Clients.getClientsList().remove(client);
        
        updateClientPanel();
    }//GEN-LAST:event_RemoveClientButtonActionPerformed

    private void SearchClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchClientButtonActionPerformed
        
        ClientCatalogue.setText("");
        for(int i = 0; i < getClientsList().size();){

            if(getClientsList().get(i).getClientName().equalsIgnoreCase(SearchClientField.getText())){
                Clients client = getClientsList().get(i);
                ClientCatalogue.setText(" Name: " + client.getClientName() + " Vehicle: " + client.getClientCar());
                System.out.println(client);
                break;
            }else{
                i++;
            }
        }
    }//GEN-LAST:event_SearchClientButtonActionPerformed
    
    private void updateClientPanel(){
        ClientCatalogue.setText("");
        for(Clients client: Clients.getClientsList()){
            ClientCatalogue.append("Name: "+ client.getClientName() + " Vehicle: "  + client.getClientCar() + "\n");
        }
        
        RemoveClientBox.removeAllItems();
        for(Clients client: Clients.getClientsList()){
            RemoveClientBox.addItem(client.getClientName());
        
       }
        
        UpdateClientBox.removeAllItems();
        for(Clients client: Clients.getClientsList()){
            UpdateClientBox.addItem(client.getClientName());
        }
    }
    
    /**
     * Below this is services
     * @param evt 
     */
    private void AddServiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddServiceButtonActionPerformed
        int employeeIndex = AddServiceEmployee.getSelectedIndex();
        Employees employee = Employees.getEmployeeList().get(employeeIndex);
        
        int clientIndex = AddServiceClient.getSelectedIndex();
        Clients client = Clients.getClientsList().get(clientIndex);
        
        String problem = AddServiceProblem.getText();
        
        double cost = Double.parseDouble(AddServiceCost.getText());
        
        Services service = new Services(employee,client,problem,cost);
        Services.getServicesList().add(service);
    }//GEN-LAST:event_AddServiceButtonActionPerformed

    private void RefreshServiceCatalogueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshServiceCatalogueActionPerformed
        ServiceCatalogue.setText("");
        for(Services service: Services.getServicesList()){
            
            String employee = service.getEmployee().getEmployeeName();
            String client = service.getClient().getClientName();
            String problem = service.getCarService();
            double cost = service.getServiceCost();
            
            ServiceCatalogue.append("Employee: " + employee + "\n" +
                                                   "Client: " + client + "\n" +
                                                   "Problem:" + "\n" + problem + "\n" +
                                                   "Cost: " + cost + "\n" +
                                                   "---------------------------------------" + "\n");
        }
    }//GEN-LAST:event_RefreshServiceCatalogueActionPerformed
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCarButton;
    private javax.swing.JButton AddClientButton;
    private javax.swing.JTextField AddClientName;
    private javax.swing.JComboBox<String> AddClientVehicle;
    private javax.swing.JButton AddEmployeeButton;
    private javax.swing.JPanel AddEmployeePanel;
    private javax.swing.JButton AddServiceButton;
    private javax.swing.JComboBox<String> AddServiceClient;
    private javax.swing.JTextField AddServiceCost;
    private javax.swing.JComboBox<String> AddServiceEmployee;
    private javax.swing.JTextArea AddServiceProblem;
    private javax.swing.JTabbedPane AppointmentPanel;
    private javax.swing.JTextArea CarCatalogue;
    private javax.swing.JTextField CarMake;
    private javax.swing.JTextField CarModel;
    private javax.swing.JTabbedPane CarPanel;
    private javax.swing.JTextArea ClientCatalogue;
    private javax.swing.JButton ClientCatalogueButton;
    private javax.swing.JTabbedPane ClientPanel;
    private javax.swing.JComboBox<String> DeleteCarBox;
    private javax.swing.JButton DeleteCarButton;
    private javax.swing.JPanel EditEmployeePanel;
    private javax.swing.JTextArea EmployeeCatalogue;
    private javax.swing.JTextField EmployeeNameAdd;
    private javax.swing.JTabbedPane EmployeePanel;
    private javax.swing.JTextField EmployeeSalaryAdd;
    private javax.swing.JButton EmployeeSearchButton;
    private javax.swing.JTextField EmployeeSearchField;
    private javax.swing.JTabbedPane Main;
    private javax.swing.JTextField NewSalary;
    private javax.swing.JButton RefreshCarCatalogue;
    private javax.swing.JButton RefreshEmployeeCatalogue;
    private javax.swing.JButton RefreshServiceCatalogue;
    private javax.swing.JComboBox<String> RemoveClientBox;
    private javax.swing.JButton RemoveClientButton;
    private javax.swing.JComboBox<String> RemoveEmployeeBox;
    private javax.swing.JButton RemoveEmployeeButton;
    private javax.swing.JComboBox<String> RemoveServiceBox;
    private javax.swing.JButton RemoveServiceButton;
    private javax.swing.JTabbedPane ReportPanel;
    private javax.swing.JButton SearchCarButton;
    private javax.swing.JTextField SearchCarField;
    private javax.swing.JButton SearchClientButton;
    private javax.swing.JTextField SearchClientField;
    private javax.swing.JButton SearchServiceButton;
    private javax.swing.JTextArea ServiceCatalogue;
    private javax.swing.JTabbedPane ServicesPanel;
    private javax.swing.JComboBox<String> UpdateCarBox;
    private javax.swing.JButton UpdateCarButton;
    private javax.swing.JComboBox<String> UpdateClientBox;
    private javax.swing.JButton UpdateClientButton;
    private javax.swing.JComboBox<String> UpdateClientVehicle;
    private javax.swing.JComboBox<String> UpdateEmployeeBox;
    private javax.swing.JButton UpdateEmployeeButton;
    private javax.swing.JTextField UpdateMakeField;
    private javax.swing.JTextField UpdateModelFeild;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
